# Generated by Django 4.0.3 on 2022-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courtcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.IntegerField(blank=True, null=True, unique=True)),
                ('defendant', models.CharField(max_length=200)),
                ('defendant_address', models.CharField(max_length=1000)),
                ('crimetype', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('arresting_officer', models.CharField(max_length=200)),
                ('when_arrested', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('presiding_judge', models.CharField(max_length=200)),
                ('public_prosecuter', models.CharField(max_length=200)),
                ('lawyer', models.CharField(max_length=200)),
                ('starting_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('judgement_date', models.DateField(blank=True, null=True)),
                ('attending_judge', models.CharField(blank=True, max_length=200)),
                ('judgement_summary', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='hearing_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='hearing_details',
            fields=[
                ('cin', models.IntegerField(primary_key=True, serialize=False, verbose_name='CIN')),
                ('date', models.DateField()),
                ('hearing_summary', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='judgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.IntegerField()),
                ('judgement_date', models.DateField(blank=True, null=True)),
                ('attending_judge', models.CharField(blank=True, max_length=200)),
                ('judgement_summary', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='search_by_cin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.IntegerField()),
            ],
        ),
    ]
